# Generated by Django 3.1 on 2020-08-10 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20200805_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='post_date',
        ),
    ]
